### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by qlaffont** [Xilixir/FortniteAPI#1]
Hi, 
Is it possible to know precisely the process you used to convert your librairy in JavaScript ?
Regards
Quentin

**Comment by qlaffont** [comment]
For me you do a auth2 request (with launcher client) -> You get a new token -> you access to the api

**Comment by julian-exile** [comment]
My library is written in Java, not Javascript.

The authorization is here
https://github.com/Xilixir/FortniteAPI/blob/master/src/main/java/com/xilixir/fortniteapi/FortniteAPI.java

**Comment by qlaffont** [comment]
Yes i know. Okay now i know how it's work i have use two headers like you say in your README but i don't know why i get: 
```
com.google.api.client.http.HttpResponseException: 400 Bad Request
{
  "errorCode" : "errors.com.epicgames.common.oauth.invalid_client",
  "errorMessage" : "It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.",
  "messageVars" : [ ],
  "numericErrorCode" : 1011,
  "originatingService" : "com.epicgames.account.public",
  "intent" : "prod",
  "error_description" : "It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.",
  "error" : "invalid_client"
}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
	at com.xilixir.fortniteapi.OAuth.OAuthRequest.execute(OAuthRequest.java:79)
	at com.xilixir.fortniteapi.FortniteAPI.login(FortniteAPI.java:43)
	at com.xilixir.fortniteapi.FortniteAPI.<init>(FortniteAPI.java:31)
	at javaapplication1.JavaApplication1.main(JavaApplication1.java:26)
Exception in thread "main" java.lang.NullPointerException
	at com.xilixir.fortniteapi.FortniteAPI.login(FortniteAPI.java:48)
	at com.xilixir.fortniteapi.FortniteAPI.<init>(FortniteAPI.java:31)
	at javaapplication1.JavaApplication1.main(JavaApplication1.java:26)
C:\Users\qlaff\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 1 second)
```

Code
```
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.xilixir.fortniteapi.Credentials;
import com.xilixir.fortniteapi.FortniteAPI;



/**
 *
 * @author qlaff
 */
public class JavaApplication1 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        // TODO code application logic here
        Credentials credentials;
        credentials = new Credentials("MYEMAIL", "MYPASSWORD", "5addd7b6665d4a508b74e70931f59ed1", "eg1~eyJraWQiOiJ0RkMyVUloRnBUTV9FYTNxY09kX01xUVQxY0JCbTlrRkxTRGZlSmhzUkc4IiwiYWxnIjoiUFMyNTYifQ.eyJhcHAiOiJmb3J0bml0ZSIsInN1YiI6IjYzNzJjMzJlYzgxZDRhMGE5ZjZlNzlmMGQ1ZWRjMzFhIiwicnNpZCI6IjBmOWNiYWVlYWUyZDRkZWE4MWFmMTMwYzMzNmRmMzk5IiwiY2xpZCI6ImVjNjg0YjhjNjg3ZjQ3OWZhZGVhM2NiMmFkODNmNWM2IiwiYW0iOiJleGNoYW5nZV9jb2RlIiwic3NpZCI6ImEyOTJhZjk1YjU5YzQyMDBhMjM3MjMwN2RjNDRmYmE4IiwicCI6ImVOcXRWdHR1NGpBUVwvWitxV3BWTEwxamlBWFZWcVJLcnJzUSs3QnVhMnBQZ3hmRkV0a1BwMytcL1lKRkNnYk1MU3Q4UWV6NXc1YzNLY3lxT2JhaDlFUmk1WUhWRGNEZTc3Y3RCSCtkQlRRN2lCVVhhSDk2UHNSdDJpa29NZWpQdlgyOWpTVWFaTit4bHhOZTdkWG9PVVZOa2d5dXJWYUNtYTF5dk9pSldCNEVBdXRjMmJmYVY5YWVBZGNvZFlJQWVlZzB3YXFwUVA1Q0JINGQ5OXdJSzNTM1NlTEFpUElYQWx2OFhRbXZvMGZGd0hkQmJNcEFvTEgrTVlxZzRtUWVhU1RWaWdKVnBCWVlGdWh0NXJzdjZKM0dTeisyaDBqSDdZNFM4NEJ2TElSaGRvbWVQenluZUtKY2UxalY3eDlKamR1RktkclFGeDlhK0pjdGU3SW9yZXJDRlFNWHhkbENWem43cm5GTzFvdHdVSW1OMUk5VHc5dkdFT0JRb0gyc3pyZlBPZzVSTERlSGhDQTdISkxqcjlvS0htWWU3SXhHeHBScEh0N1pBZ3lFVUJTYlM3dHY2UXRsMTZ1d1RuUmpDeldzYVwvWDJuOVl2R2JoOVVlUG9kcHhHZUpjSVp1cFNYdWFmSFROclZkOGVaNGRGaE80Q3J5ZFBlRlwvZjBBMmZUbU5cL0MwOVFFc3creFwvWVpubmw5a1JoUmNuXC9Ua2JIaVZsN01GSE8zTGNDbHIrekhsdEFRNlZvQ3pqR21uamhDMDY5Q1hQcllOUkR3NHFKblUzRmxoTHdwOWxmWjBQc1g4RlVCQ1NKM2MwcDQybFwvSThaN1grVW5aM3o0T0RGbzU1cVc2MmJZWis0TFF6UnNpcTNsOGF6dWt6QkgwK1wva1RPcXpaXC9hXC9ldHJPWmxZNVVpcmhwVjBMXC9Cb0s2dlF0V0pwclZWNzBKR3FhNXA1dzVQVVlFUkFLTHl3WG1TV25hbGV6QjFWWlZwOXFsRjh4OVVVQXZwb1g0ZFhqMXlBemZGWGROQkhVcmdIdnV0XC8wR2x1Tjc4bytcL2ZQeGVRM3JMOGFrc3YwVWJVRDVQdXpNdHlNU2I5Y3RYcGxhdmd2M1FHRUl3PT0iLCJpYWkiOiI2MzcyYzMyZWM4MWQ0YTBhOWY2ZTc5ZjBkNWVkYzMxYSIsImNsc3ZjIjoiZm9ydG5pdGUiLCJpYyI6ZmFsc2UsImV4cCI6MTUxMjI0ODcyNywiaWF0IjoxNTEyMjE5OTI3LCJqdGkiOiI4NDFiNjY0M2ZmN2M0MTI5ODVlOWE5MjVlNTVjNDNhMyJ9.Aj2h5Aad-FuKMjMkBIJ7grA-IVaulRzcEXYzwrveBUFRq8V5W8V5zBLCLgw0CopIWw8JzliMP4execasZK6WpN0X");
        FortniteAPI test = new FortniteAPI(credentials );
    }
    
}

```
How you know it is the good header ?

**Comment by julian-exile** [comment]
The credentials you're using are wrong - the 3rd and 4th arguments are base64, and you're using what seems to be a refresh token and an auth token.

The base64 hashes you want are in the Authorization header when you login to the client and when you login to the game, both prefixed by the word "basic" in the header.

**Comment by qlaffont** [comment]
Thanks, it work last question and after that i leave you and i give you some cash because you need it ;). When you know you need to refresh token ? with refreshToken function ?

**Comment by julian-exile** [comment]
Whenever you authenticate or refresh your token, the return value (OAuthData) contains a field called 'expires_in' and one called 'expires_at'. These tell you when your authentication will expire, however you can stop it from expiring by refreshing the token before it expires, which I do in the refreshToken method.

**Comment by VoltexYT** [comment]
How to get the auth token?
