### ISSUE TITLE
Why not work?

### ISSUE THREAD

**Issue by VoltexYT** [Xilixir/FortniteAPI#5]
How to get Hash pair from epic launcher and the Hash pair from launching fortnite

com.google.api.client.http.HttpResponseException: 400 Bad Request
{
  "errorCode" : "errors.com.epicgames.common.oauth.invalid_client",
  "errorMessage" : "It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.",
  "messageVars" : [ ],
  "numericErrorCode" : 1011,
  "originatingService" : "com.epicgames.account.public",
  "intent" : "prod",
  "error_description" : "It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.",
  "error" : "invalid_client"
}
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at com.xilixir.fortniteapi.v2.FortniteAPI.authenticate(FortniteAPI.java:62)
        at voltex.ts3.events.TS3Events$1.onClientJoin(TS3Events.java:93)
        at com.github.theholywaffle.teamspeak3.api.event.ClientJoinEvent.fire(ClientJoinEvent.java:177)
        at com.github.theholywaffle.teamspeak3.EventManager.fireEvent(EventManager.java:55)
        at com.github.theholywaffle.teamspeak3.SocketReader$1.run(SocketReader.java:99)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by julian-exile** [comment]
The error message is right in front of you, and you need to use Fiddler to get the auth hashes.

**Comment by VoltexYT** [comment]
How?

**Comment by VoltexYT** [comment]
how to use fiddler
